In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

In [2]:
tf.reset_default_graph()
# you can't write x = tf.constant(np.array([1, 2, 3], dtype=np.float32))
# since tensorflow does not have the promotion machenism like numpy
# the rank of the input tensor for tf.tile must be the same the length of `multiples`
x = tf.constant(np.array([[1, 2, 3]], dtype=np.float32))
tile_x_op = tf.tile(x, [3, 1])
print(x.shape)

(1, 3)


In [3]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    x_tile = sess.run(tile_x_op)
    print(x_tile)

[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
